// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SchoolOnboardingAPI.Data;

#nullable disable

namespace SchoolOnboardingAPI.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SchoolOnboardingAPI.Models.AssetAssignment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AssetTag")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("AssignedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("ConditionNotes")
                        .HasColumnType("text");

                    b.Property<int>("PersonId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ReturnedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("SnipeItAssetId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AssetTag")
                        .IsUnique()
                        .HasDatabaseName("idx_asset_assignment_tag");

                    b.HasIndex("PersonId")
                        .HasDatabaseName("idx_asset_assignment_person_id");

                    b.HasIndex("ReturnedAt")
                        .HasDatabaseName("idx_asset_assignment_returned");

                    b.HasIndex("SnipeItAssetId")
                        .HasDatabaseName("idx_asset_assignment_snipeit_id");

                    b.ToTable("AssetAssignments");
                });

            modelBuilder.Entity("SchoolOnboardingAPI.Models.AuditLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("ChangedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("ChangedBy")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("EntityId")
                        .HasColumnType("int");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("NewValue")
                        .HasColumnType("text");

                    b.Property<string>("OldValue")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Action")
                        .HasDatabaseName("idx_audit_log_action");

                    b.HasIndex("ChangedAt")
                        .HasDatabaseName("idx_audit_log_changed_at");

                    b.HasIndex("ChangedBy")
                        .HasDatabaseName("idx_audit_log_changed_by");

                    b.HasIndex("EntityType", "EntityId")
                        .HasDatabaseName("idx_audit_log_entity");

                    b.ToTable("AuditLogs");
                });

            modelBuilder.Entity("SchoolOnboardingAPI.Models.LifecycleRequest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("EffectiveDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Notes")
                        .HasColumnType("text");

                    b.Property<int>("PersonId")
                        .HasColumnType("int");

                    b.Property<string>("RequestType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasDefaultValue("pending");

                    b.Property<string>("SubmittedBy")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("SubmittedRole")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("PersonId")
                        .HasDatabaseName("idx_lifecycle_request_person_id");

                    b.HasIndex("Status")
                        .HasDatabaseName("idx_lifecycle_request_status");

                    b.HasIndex("PersonId", "RequestType")
                        .HasDatabaseName("idx_lifecycle_request_person_type");

                    b.ToTable("LifecycleRequests");
                });

            modelBuilder.Entity("SchoolOnboardingAPI.Models.LifecycleTask", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Completed")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("LifecycleRequestId")
                        .HasColumnType("int");

                    b.Property<string>("Notes")
                        .HasColumnType("text");

                    b.Property<bool>("Required")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("TaskType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("Completed")
                        .HasDatabaseName("idx_lifecycle_task_completed");

                    b.HasIndex("LifecycleRequestId")
                        .HasDatabaseName("idx_lifecycle_task_request_id");

                    b.HasIndex("TaskType")
                        .HasDatabaseName("idx_lifecycle_task_type");

                    b.ToTable("LifecycleTasks");
                });

            modelBuilder.Entity("SchoolOnboardingAPI.Models.Person", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Identifier")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasComment("student_id or staff_id");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Notes")
                        .HasColumnType("text");

                    b.Property<string>("PersonType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("RoleOrHomeroom")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime?>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasDefaultValue("active");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("Identifier")
                        .IsUnique()
                        .HasDatabaseName("idx_person_identifier");

                    b.HasIndex("PersonType")
                        .HasDatabaseName("idx_person_type");

                    b.HasIndex("Status")
                        .HasDatabaseName("idx_person_status");

                    b.ToTable("People");
                });

            modelBuilder.Entity("SchoolOnboardingAPI.Models.TicketLink", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("LifecycleRequestId")
                        .HasColumnType("int");

                    b.Property<int>("OsTicketTicketId")
                        .HasColumnType("int");

                    b.Property<string>("TicketType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("LifecycleRequestId")
                        .HasDatabaseName("idx_ticket_link_request_id");

                    b.HasIndex("OsTicketTicketId")
                        .IsUnique()
                        .HasDatabaseName("idx_ticket_link_osticket_id");

                    b.ToTable("TicketLinks");
                });

            modelBuilder.Entity("SchoolOnboardingAPI.Models.AssetAssignment", b =>
                {
                    b.HasOne("SchoolOnboardingAPI.Models.Person", "Person")
                        .WithMany("AssetAssignments")
                        .HasForeignKey("PersonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_asset_assignment_person");

                    b.Navigation("Person");
                });

            modelBuilder.Entity("SchoolOnboardingAPI.Models.LifecycleRequest", b =>
                {
                    b.HasOne("SchoolOnboardingAPI.Models.Person", "Person")
                        .WithMany("LifecycleRequests")
                        .HasForeignKey("PersonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_lifecycle_request_person");

                    b.Navigation("Person");
                });

            modelBuilder.Entity("SchoolOnboardingAPI.Models.LifecycleTask", b =>
                {
                    b.HasOne("SchoolOnboardingAPI.Models.LifecycleRequest", "LifecycleRequest")
                        .WithMany("Tasks")
                        .HasForeignKey("LifecycleRequestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_lifecycle_task_request");

                    b.Navigation("LifecycleRequest");
                });

            modelBuilder.Entity("SchoolOnboardingAPI.Models.TicketLink", b =>
                {
                    b.HasOne("SchoolOnboardingAPI.Models.LifecycleRequest", "LifecycleRequest")
                        .WithMany("TicketLinks")
                        .HasForeignKey("LifecycleRequestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_ticket_link_request");

                    b.Navigation("LifecycleRequest");
                });

            modelBuilder.Entity("SchoolOnboardingAPI.Models.LifecycleRequest", b =>
                {
                    b.Navigation("Tasks");

                    b.Navigation("TicketLinks");
                });

            modelBuilder.Entity("SchoolOnboardingAPI.Models.Person", b =>
                {
                    b.Navigation("AssetAssignments");

                    b.Navigation("LifecycleRequests");
                });
#pragma warning restore 612, 618
        }
    }
}
